### ISSUE TITLE
Varias dudas

### ISSUE THREAD

**Issue by matiasmasca** [nulinga/tentative-courses#1]
Me surgen las siguientes dudas:
-  Qué horario debería tener el curso individual? el primero que haga la igualdad con el alumno? o con el profesor?

-  Qué horario debería tener el curso grupal? el primero que haga la igualdad con todos los alumnos? o el primero con la disponibilidad del profesor profesor?

- datos obligatorios y datos por defecto cuando no estén. Por ejemplo para estudiantes.

- Cantidad de horarios mínimos para docentes.

- duración de las clases? tiempo de descanso entre clases?

- un estudiante puede tener 2 inscripciones y por ende estar en 2 cursos? por ejemplo uno grupal y uno individual? un de tipo negocio y otro de conversación. Sobre todo en los casos donde el estudiante manifestó tener varios horarios disponibles.

**Comment by jvillarejo** [comment]
Buenas Matías.

* Se deberían mostrar todas las posibilidades para asignar los grupos con todos los docentes

* Se deberían mostrar todas las posibilidades de agrupación con los docentes

* Asumí que van a estar todos los datos completos a ninguno le va a faltar datos necesarios

* No hay horarios mínimos

* 1 hora de duración, no se contempla descanso

* Sólo una inscripción puede tener el estudiante. Manifestar multiples horarios disponibles es para ampliar la posibilidad de asignación con docente.

Saludos!
